// ╔═════════════════════════╗
// ║  RSI Simple BlackBox    ║
// ║  @Ultr.                 ║
// ╚═════════════════════════╝

//@version=5
indicator("RSI Bandas Sup & Inf [@Ultr.]", shorttitle="RSI Bandas(@Ultr)", overlay=false)

//  ════════════════
//  ═══  Simple  ═══
//  ═══  Colors  ═══

//  ═══  Standard  ═══
	// color colorAqua				= color.aqua			// #00BCD4  Aqua
	// color colorBlueSky10			= input.color(#59F2E9)  //
	// color colorBlueSky20			= input.color(#39F0EA)  //
	// color colorBlueSky30			= input.color(#01EBF9)  // EEG Light Blue
	// color colorBlueSky40			= input.color(#00E7FD)  // EEG Light Blue
	// color colorLightBlueSky50	= input.color(#12cef8)  // Celeste
	// color colorMenta10			= input.color(#E0F9EF)
	// color colorMenta20			= input.color(#80F3EC)  //
	// color colorMenta30			= input.color(#7FFFD4)  //
	// color colorMenta40			= input.color(#73FFCA)  //
	// color colorLightMenta50		= input.color(#00ffd5)  // Menta
	// color colorBlue  			= color.blue			// #2196F3  Blue
	// color colorBlue50			= input.color(#0034c5)
	// color colorTeal				= color.teal			// #00897B  Teal
	// color colorGreen				= color.green			// #4CAF50  Green
	// color colorOlive				= color.olive			// #808000  Olive
	// color colorLime				= color.lime			// #00E676  Lime
	// color colorLightGreen50		= input.color(#33ffac)
	// color colorYellow			= color.yellow			// #FFEB3B  Yellow
	// color colorLightYellow50		= input.color(#eedd45)
	// color colorOrange			= color.orange			// #FF9800  Orange
	// color colorMaroon			= color.maroon			// #880E4F  Maroon
	// color colorRed				= color.red				// #FF5252  Red
	// color colorNitRed40			= input.color(#e91e63)
	// color colorNitRed50			= input.color(#de0011)
	// color colorFucsia40			= input.color(#FF00B1)  // EEG Fucsia
	// color colorFucsia50			= input.color(#FE0CB6)  // EEG Fucsia
	// color colorFuchsia			= color.fuchsia			// #E040FB  Fuchsia
	// color colorPurple			= color.purple			// #9C27B0  Purple
	// color colorNavy				= color.navy			// #311B92  Navy
	// color colorBlack				= color.black			// #363A45  Black
	// color colorGray				= color.gray			// #787B86  Gray
	// color colorSilver			= color.silver			// #B2B5BE  Silver
	// color colorWhite				= color.white			// #FFFFFF  White

//  ═══  Ameritrade  ═══
	//  colorWhite					= input.color(#FFFFFF)
	//  colorGrayPlatinum			= input.color(#F7F7F7)
	//  colorGrayNickel				= input.color(#F1F1F1)
	//  colorGrayNickelDark20		= input.color(#C0C0C0)
	//  colorGrayAluminum			= input.color(#E6E7E9)
	//  colorGrayAsh				= input.color(#D8D8D8)
	//  colorGrayStone				= input.color(#999999)
	//  colorGrayIron				= input.color(#666666)
	//  colorGrayCharcoal			= input.color(#333333)
	//  colorBlack					= input.color(#000000)
	//  colorGreenCabbage			= input.color(#EBF6E9)
	//  colorGreenVerdeLight70		= input.color(#B4D6B2)
	//  colorGreenVerdeLight50		= input.color(#83BC7F)
	//  colorGreenVerdeNat			= input.color(#40a829)
	//  colorGreenVerdeLight20		= input.color(#399333)
	//  colorGreenVerde				= input.color(#087900)
	//  colorGreenVerdeDark20		= input.color(#066000)
	//  colorGreenMoss				= input.color(#BEE7D3)
	//  colorGreenMint				= input.color(#6DC4BC)
	//  colorGreenPine				= input.color(#38635A)
	//  colorRedRose				= input.color(#FAD1CF)
	//  colorRedRojaLight50			= input.color(#E08988)
	//  colorRedRojaLight20			= input.color(#CD4241)
	//  colorRedRoja				= input.color(#C11312)
	//  colorRedRojaDark20			= input.color(#940F0E)
	//  colororangePeach			= input.color(#FCE7CA)
	//  colororangeCarrot			= input.color(#ED8902)
	//  colororangeYam				= input.color(#BD5310)
	//  colorblueFrost				= input.color(#E1EEF9)
	//  colorblueLagoon				= input.color(#316486)
	//  colorblueNavy				= input.color(#2A5673)
	//  colorblueNcean				= input.color(#64A1C6)
	//  colorpurpleEggPlant 		= input.color(#732181)

//  ═══  Axi  ═══
	//  colorGlobalPrimary			= input.color(#fc404d)
	//  colorGlobalSecondary		= input.color(#282424)
	//  colorGlobalAccent			= input.color(#61ce70)
	//  colorGlobal-7a46f22			= input.color(#d11c36)
	//  colorGlobal-1519066c		= input.color(#fc404d)
	//  colorGlobal-3d4fa1a1		= input.color(#f0ebe3)
	//  colorGlobal-638b46c1		= input.color(#fcd758)
	//  colorGlobal-d07bac9			= input.color(#f9b4a8)
	//  colorGlobal-e63a114			= input.color(#2c4d5a)
	//  colorGlobal-8bf0845			= input.color(#a4d866)
	//  colorGlobal-75c6da1			= input.color(#282424)
	//  colorGlobal-378280f			= input.color(#45c2c7)
	//  colorGlobal-4de92c5			= input.color(#6caddf)
	//  colorGlobal-413dab8			= input.color(#00275d)
	//  colorGlobal-b3fab89			= input.color(#55165c)
	//  colorGlobal-548138f			= input.color(#45c2c7)
	//  colorGlobal-5ed9920			= input.color(#ea1616)
	//  colorGlobal-70f7335			= input.color(#dd0606)

//  ═══  GrayScale  ═══
	//  colorFocus					= input.color(#2d7aed)
	//  colorWhite					= input.color(#fff)
	//  colorBlack					= input.color(#000)
	//  colorPrimaryBlackberry		= input.color(#2e234b)
	//  colorPrimaryBlackberry40	= input.color(rgba(46, 35, 75, .4))
	//  colorPrimaryBlackberry65	= input.color(rgba(46, 35, 75, .65))
	//  colorPrimaryCoral			= input.color(#ffb198)
	//  colorSecondaryForestGreen	= input.color(#244024)
	//  colorSecondaryKeyLime		= input.color(#b5ce6f)
	//  colorSecondaryLavender		= input.color(#c5bfe4)
	//  colorSecondaryLavender40	= input.color(rgba(197, 191, 228, .4))
	//  colorsecondaryLavender60	= input.color(rgba(197, 191, 228, .6))
	//  colorhoverWhite				= input.color(#c0bdc9)
	//  colorhoverBlackberry		= input.color(#42326b)
	//  colordisabledBlackberry		= input.color(#4d4466)
	//  coloractiveBlackberry		= input.color(#4d4466)
	//  colorhoverCcoral			= input.color(#ffcdbd)
	//  coloractiveCcoral			= input.color(#ff9e80)
	//  colorhoverGray				= input.color(#827b93)
	//  colorhoverGray2				= input.color(#6d6581)
	//  colorgrayCharcoal			= input.color(#282525)
	//  colorgrayCharcoal70			= input.color(rgba(40, 37, 37, .7))
	//  colorgrayCharcoal80			= input.color(rgba(40, 37, 37, .8))
	//  colorgrayLight				= input.color(#f5f5f5)
	//  colorgrayMedium				= input.color(#eee)
	//  colorgray70					= input.color(#696666)
	//  colorgrayDark				= input.color(#c1c1c1)
	//  colorwebSeasalt				= input.color(#fafafc)
	//  colorwebDivider				= input.color(#e9e7f1)
	//  colorwebBackground			= input.color(#f3f2fa)
	//  colorwebSecondaryText		= input.color(#77708a)
	//  colorwebStroke				= input.color(#d3ceeb)
	//  colorwebErrors				= input.color(#e00000)
	//  colorwebService				= input.color(#2d7aed)

//  ═══  Interactive  ═══
	//  coloPrimary3		= input.color(hsla(355, 85%, 46%, 0.03))
	//  coloPrimary5		= input.color(hsla(355, 85%, 46%, 0.05))
	//  coloPrimary10		= input.color(hsla(355, 85%, 46%, 0.10))
	//  coloPrimary20		= input.color(hsla(355, 85%, 46%, 0.20))
	//  coloPrimary30		= input.color(hsla(355, 85%, 46%, 0.30))
	//  coloPrimary40		= input.color(hsla(355, 85%, 46%, 0.40))
	//  coloPrimary50		= input.color(hsla(355, 85%, 46%, 0.50))
	//  coloPrimary60		= input.color(hsla(355, 85%, 46%, 0.60))
	//  coloPrimary70		= input.color(hsla(355, 85%, 46%, 0.70))
	//  coloPrimary80		= input.color(hsla(355, 85%, 46%, 0.80))
	//  coloPrimary90		= input.color(hsla(355, 85%, 46%, 0.90))
	//  coloPrimary			= input.color(hsla(355, 85%, 46%, 1.0))
	//  coloPrimaryDark10	= input.color(hsla(355, 85%, 41%, 1.0))
	//  coloPrimaryDark20	= input.color(hsla(355, 85%, 36%, 1.0))
	//  coloPrimaryDark30	= input.color(hsla(355, 85%, 31%, 1.0))
	//  coloPrimaryDark40	= input.color(hsla(355, 85%, 26%, 1.0))
	//  coloPrimaryDark50	= input.color(hsla(355, 85%, 21%, 1.0))
	//  coloSecondary3		= input.color(hsla(0, 0%, 13%, 0.03))
	//  coloSecondary5		= input.color(hsla(0, 0%, 13%, 0.05))
	//  coloSecondary10		= input.color(hsla(0, 0%, 13%, 0.10))
	//  coloSecondary20		= input.color(hsla(0, 0%, 13%, 0.20))
	//  coloSecondary30		= input.color(hsla(0, 0%, 13%, 0.30))
	//  coloSecondary40		= input.color(hsla(0, 0%, 13%, 0.40))
	//  coloSecondary50		= input.color(hsla(0, 0%, 13%, 0.50))
	//  coloSecondary60		= input.color(hsla(0, 0%, 13%, 0.60))
	//  coloSecondary70		= input.color(hsla(0, 0%, 13%, 0.70))
	//  coloSecondary80		= input.color(hsla(0, 0%, 13%, 0.80))
	//  coloSecondary90		= input.color(hsla(0, 0%, 13%, 0.90))
	//  coloSecondary		= input.color(hsla(0, 0%, 13%, 1.0))
	//  coloSecondaryDark10	= input.color(hsla(0, 0%, 10%, 1.0))
	//  coloSecondaryDark20	= input.color(hsla(0, 0%, 7%, 1.0))
	//  coloSecondaryDark30	= input.color(hsla(0, 0%, 4%, 1.0))
	//  coloSecondaryDark40	= input.color(hsla(0, 0%, 1%, 1.0))
	//  coloSecondaryDark50	= input.color(hsla(0, 0%, 0%, 1.0))
	//  coloTertiary3		= input.color(hsla(202, 76%, 19%, 0.03))
	//  coloTertiary5		= input.color(hsla(202, 76%, 19%, 0.05))
	//  coloTertiary10		= input.color(hsla(202, 76%, 19%, 0.10))
	//  coloTertiary20		= input.color(hsla(202, 76%, 19%, 0.20))
	//  coloTertiary30		= input.color(hsla(202, 76%, 19%, 0.30))
	//  coloTertiary40		= input.color(hsla(202, 76%, 19%, 0.40))
	//  coloTertiary50		= input.color(hsla(202, 76%, 19%, 0.50))
	//  coloTertiary60		= input.color(hsla(202, 76%, 19%, 0.60))
	//  coloTertiary70		= input.color(hsla(202, 76%, 19%, 0.70))
	//  coloTertiary80		= input.color(hsla(202, 76%, 19%, 0.80))
	//  coloTertiary90		= input.color(hsla(202, 76%, 19%, 0.90))
	//  coloTertiary		= input.color(hsla(202, 76%, 19%, 1.0))
	//  coloTertiaryDark10 	= input.color(hsla(202, 76%, 14%, 1.0))
	//  coloTertiaryDark20 	= input.color(hsla(202, 76%, 9%, 1.0))
	//  coloTertiaryDark30 	= input.color(hsla(202, 76%, 4%, 1.0))
	//  coloTertiaryDark40 	= input.color(hsla(202, 76%, 0%, 1.0))

//  ═══  Latam  ═══
	//  colorRedBackground			= input.color(rgb(232, 17, 75))	//Rojo Latam

//  ═══  Basic  ═══
    // var grpColor = " ═══ Colores ═══ "
    // color colorBlueSky10				= input.color(#59F2E9)                   //
    // color colorBlueSky20				= input.color(#39F0EA)                   //
    // color colorBlueSky30				= input.color(#01EBF9)                   // EEG Light Blue
    // color colorBlueSky40				= input.color(#00E7FD)                   // EEG Light Blue
    // color colorLightBlueSky50		= input.color(#12cef8)                   // Celeste  // // Top Long Buy
    // color colorMenta10				= input.color(#E0F9EF)
    // color colorMenta20				= input.color(#80F3EC)                   //
    // color colorMenta30				= input.color(#7FFFD4)                   //
    // color colorMenta40				= input.color(#73FFCA)                   //
    // color colorLightMenta50			= input.color(#00ffd5)                   // Menta
    // color colorBlue50				= input.color(#0034c5)                   // Blue Light
    // color colorLightGreen50			= input.color(#33ffac)                   // Green Light
    // color colorLightYellow50			= input.color(#eedd45)                   // Yellow
    // color colorNitRed40				= input.color(#e91e63)                   // Red Light  // // Bottom Short Sell
    // color colorNitRed50				= input.color(#de0011)                   
    // color colorFucsia40				= input.color(#FF00B1)                   // EEG Fucsia
    // color colorFucsia50				= input.color(#FE0CB6)                   // EEG Fucsia

    // color colorGrayAluminum			= input.color(#E6E7E9)
    // color colorGlobalPrimary			= input.color(#fc404d)
    // color colorGlobal5ed9920			= input.color(#ea1616)
    // color colorGlobal70f7335			= input.color(#dd0606)
    // color colorGlobal7a46f22			= input.color(#d11c36)
    // color colorPrimaryBlackberry		= input.color(#2e234b)
    // color colorSecondaryForestGreen	= input.color(#244024)
    // color colorSecondaryLavender		= input.color(#c5bfe4)
    // color colorWebSeasalt			= input.color(#fafafc)
    // color colorWebDivider			= input.color(#e9e7f1)
    // color colorWebBackground			= input.color(#f3f2fa)
    // color colorRedBackground			= input.color(rgb(232, 17, 75))	 		// Rojo Latam
    // color colorLilBackground			= input.color(rgb(126, 87, 194, 90))	// Lila
    // color colorLyla					= input.color(#7E57C2)					// Lila
    // color colorLightGray				= input.color(#787B86)					// Gray


//  ═══  Basic  ═══
var grpColor = " ═══ Colores ═══ "
color colorBlueSky10				= #59F2E9                   //
color colorBlueSky20				= #39F0EA                   //
color colorBlueSky30				= #01EBF9                   // EEG Light Blue
color colorBlueSky40				= #00E7FD                   // EEG Light Blue
color colorLightBlueSky50			= #12cef8                   // Celeste  // // Top Long Buy
color colorMenta10					= #E0F9EF
color colorMenta20					= #80F3EC                   //
color colorMenta30					= #7FFFD4                   //
color colorMenta40					= #73FFCA                   //
color colorLightMenta50				= #00ffd5                   // Menta
color colorBlue50					= #0034c5                   // Blue Light
color colorLightGreen50				= #33ffac                   // Green Light
color colorLightYellow50			= #eedd45                   // Yellow
color colorNitRed40					= #e91e63                   // Red Light  // // Bottom Short Sell
color colorNitRed50					= #de0011                   
color colorFucsia40					= #FF00B1                   // EEG Fucsia
color colorFucsia50					= #FE0CB6                   // EEG Fucsia
color colorGrayAluminum				= #E6E7E9
color colorGlobalPrimary			= #fc404d
color colorGlobal5ed9920			= #ea1616
color colorGlobal70f7335			= #dd0606
color colorGlobal7a46f22			= #d11c36
color colorPrimaryBlackberry		= #2e234b
color colorSecondaryForestGreen		= #244024
color colorSecondaryLavender		= #c5bfe4
color colorWebSeasalt				= #fafafc
color colorWebDivider				= #e9e7f1
color colorWebBackground			= #f3f2fa
color colorLyla						= #7E57C2					// Lila
color colorLightGray				= #787B86					// Gray


//  ════════════════
//  ═══  Simple  ═══
//  ═══  Variables  ═══

var grpValores  = " ═══ Valores ═══ "
rsiLength       =   input(defval = 14,  title = "Longitud")
overBoughtHigh  =   input(defval = 75,  title = "Sobrecompra Maximo")
overBought      =   input(defval = 70,  title = "Sobrecompra")
overSold        =   input(defval = 30,  title = "Sobreventa")
overSoldSlow    =   input(defval = 25,  title = "Sobreventa Minimo")

//  ════════════════
//  ═══  Simple  ═══
//  ═══  Types  ═══

type OHL
    float O = open
    float H = high
    float L = low
    float C = close
    float V = volume

//  ════════════════
//  ═══  Simple  ═══
//  ═══  Functions  ═══

ma(source, length, type) =>
	switch type
    	"SMA" => ta.sma(source, length)				// Media Movil Simple
		"EMA" => ta.ema(source, length)				// Media Movil Exponencial
		"RMA" => ta.rma(source, length)				// Media Movil Rolling
		"WMA" => ta.wma(source, length)				// Media Movil Ponderada
		"VWMA" => ta.vwma(source, length)			// Media Movil Ponderada por volumen

ohl = OHL.new()

//  ════════════════
//  ═══  Simple  ═══
//  ═══  Instances  ═══

rsi = ta.rsi(ohl.C, rsiLength)

//  ════════════════
//  ═══  Simple  ═══
//  ═══  Lines & Plots  ═══

overBoughtLine      = hline(overBought,     color = color.new(colorLightBlueSky50, 30))
overBoughtLineHigh  = hline(overBoughtHigh, editable = false, display = display.none)
overSoldLine        = hline(overSold,       color = color.new(colorNitRed40, 30))
overSoldLineSlow    = hline(overSoldSlow,   editable = false, display = display.none)

//  ════════════════
//  ═══  Simple  ═══
//  ═══  Linea Rsi  ═══

plot(rsi, title = "RSI", color = color.new(colorLightBlueSky50, 35), linewidth= 2)

//  ════════════════
//  ═══  Simple  ═══
//  ═══  Fills  ═══

//  ═══  Bandas Superior & Inferior  ═══
fill(overBoughtLine,    overBoughtLineHigh, color = color.new(colorLightBlueSky50, 70))
fill(overSoldLine,      overSoldLineSlow,   color = color.new(colorNitRed40, 70))

//  ═══  Principal  ═══
fill(overBoughtLine,    overSoldLine,       color = color.new(colorSecondaryLavender, 90))
